### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by vsoch** [pydicom/pydicom-data#1]
There are some datasets also served by deid and functions to retrieve them, so I'd be happy to add them here once there is an example I can follow.

**Comment by darcymason** [comment]
This comes from https://github.com/pydicom/pydicom/issues/1111 and https://github.com/pydicom/pydicom/issues/1114 where zenodo was used, but it seems quite difficult to update files there, so trying dowloading as needed from a repo - this one.

I've just put the pydicom ones in a 'data' folder, but could rename to 'pydicom' if you want to use this with the other repos...

**Comment by vsoch** [comment]
Ohh so you mean pydicom-data as in contributors / metadata about pydicom?

I think I had it wrong, but if you do need to update some .zenodo.json progratically I'm actually working on a GitHub action for that now that could help. If not sorry for the noise, and please feel free to close the issue.

**Comment by darcymason** [comment]
> so you mean pydicom-data as in contributors / metadata about pydicom?

Hmm, not quite, if I understand you correctly.  It is just the data/test_files directory, - most of the DICOM files from there, except some of the small ones..  It's just to keep the repo and the install package small.  Our test suite grew quite a bit over time and it is now a little too large to be carrying around with the source code and install packages.

> If you do need to update some .zenodo.json progratically

I'm not quite sure what that means, but it doesn't sound like our use case - we want to download any of the DICOM test files if not in a local cache, if that file is accessed through `pydicom.data.get_testdata_file`.  Most people won't need the majority of these files, maybe just some to play with as examples if they are new pydicom users. If they do follow a more advanced example, or want to run the test suite, the needed files will be downloaded to local cache and used from there.
